title: Suyeon Jeong
author:
  name: Suyeon Jeong
  email: suyeon.jeong20@snu.ac.kr
description: > # this means to ignore newlines until "show_excerpts:"
  Suyeon Jeong is a first-year Ph.D. student in HCDE at the Unviersity of Washington

show_excerpts: false # set to true to show excerpts on the homepage

permalink: /:title

url: "https://suyeonbc.gihub.io" # the base hostname & protocol for your site
  
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

collections:
  publication:
    output: true

theme: minima