project:
  - title: Non-Rigid Origami Dynamics Analysis
    image: origami.jpg
    detail: >
      <p>Advised by <a href='https://me.snu.ac.kr/en/snu__professor/yang-jinkyu/'>Jinkyu Yang</a>, we investigated the controllability and observability Gramian of an origami system composed of Miura-ori cells. (ready for submission)</p>

      <img src='site.baseurl/assets/images/project_detail/origamidetail.jpg' class='img-responsive' alt='keyscreen of our system'>

      <p style='text-align: center;'><b>Optimization of Structure Deployment Using State-Space Representation and Minimum-Energy Control</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Origami System Model Development, Observability Gramian Analysis</p>
    tags:
      - Research
      - Origami Structure
      - Control Theory
      - Reconfigurable Robotics
    description: >-
      Controllability-Observability Analysis of Origami Dynamics through State-Space Modeling
    id: design_card
  - title: Soft Ribbon-Fin Robotic Fish
    image: softrobot1.jpg
    detail: >
      <p>Advised by <a href='https://tolley.eng.ucsd.edu/'>Mike Tolley</a>, we develop a heavily underactuated platform inspired by gymnotiform fish, capable of a breadth of agile swimming behavior. (manuscript in preperation)</p>

      <p>Working with <a href='https://gromitchan.com/'>Iman adibnazari</a> at UCSD, I built a system that generates persona-driven design agents for poster design. (manuscript in preperation)</p>

      <p>This work was done during my exchange student at UCSD.</p>
      
      <img src='site.baseurl/assets/images/project_detail/softrobotdetail.jpg' class='img-responsive' alt='keyscreen of our system'>

      <p style='text-align: center;'><b>Control Analysis and Experimental Setup of a Biomimetic Robotic Fish</b></p>
      <hr>

      <p><b>[My role in this project]</b><br>Leading the project</p>
    tags:
      - Research
      - Soft Robotics
      - Design & Manufacturing
      - Control Theory
    description: Agile Swimming via Ribbon Fin on a Sparsely-Actuated Gymnotiform Robot
    id: customized_design_card
  - title: YoshiDeploy
    paper: chi2023_introbot_paper.pdf
    description: Yoshimura Tessellation-based Self-Deploying Helmet
    detail: >
      <p>Advised by <a href='https://www.biorobotics.snu.ac.kr/lab-members'>Kyujin Cho</a>, 
      we proposed a novel passive deployable helmet based on Yoshimura origami tessellation</p>

      <img src='site.baseurl/assets/images/project_detail/geardetail.jpg'
      class='img-responsive' alt='keyscreen of our system'>

      <p style='text-align: center;'><b>Deployable Origami Helmet Fabrication and Analysis</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Leading the project</p>
    tags:
      - Research
      - Wearable Robotics
      - Design & Fabrication
    image: gear.jpg
    id: introbot
  - title: PlayEye
    image: Playeye.jpg
    link: 'https://eng.snu.ac.kr/snu/pgm/hallOfFame/list.do?menuNo=200142&pageIndex=1&searchWnpz=WNPZ001&searchRnd=CRTV_2023_01'
    paper: Grand Prize of 2023 Creative Design Fair, Seoul National University Engineering Department
    detail: >
      <p>Working with <a href='http://younghokim.net/'>Sieun Kim</a>, <a href='http://younghokim.net/'>Minkyun Seo</a> at SNU, I built an interface that helps child to prevent Myopia.</p>

      <p>This work was done during my internship at Naver AI.</p>

      <img src='site.baseurl/assets/images/project_detail/exercise-planning.jpg' class='img-responsive' alt='keyscreen of our system'>

      <p style='text-align: center;'><b>Keyscreen of our system</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Leading the project</p>
    tags:
      - Healthcare
      - Gaze Tracking
      - Design & Fabrication
      - Computer Vision
    description: >-
      Haptic Device for Preventing Child Myopia
    id: design_card
  - title: Multi Barbell Assistant
    image: barbel.jpg
    paper: chi2024_paper2card_paper.pdf
    detail: >
      <p>Advised by <a href='https://www.llwang.net/'>Lucy Lu Wang</a> and <a href='https://faculty.washington.edu/garyhs/'>Gary Hsieh</a>, I built a system that automatically transforms design implications from HCI papers into design cards with generative AI. (CHI '24 paper)</p>

      <img src='site.baseurl/assets/images/project_detail/design-card.jpg' class='img-responsive' alt='keyscreen of our system'>

      <p style='text-align: center;'><b>Pipeline of generating design cards using our system</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Leading the project</p>
    tags:
      - Research
      - <i class='fas fa-book'></i>&nbsp; CHI '24
      - LLM
      - Design
      - Translational science
    description: >-
      Transforming design implications into design cards with generative AI
    id: design_card
  - image: swarm1.jpg
    title: Self-actuating Swarm Robot
    detail: >
      <p> Advised by <a href='https://fluids.snu.ac.kr/hyk.htm'>Hoyoung Kim</a>, we developed a self- actuating swarm robotic system that employs 
      mechanical intelligence through collective behaviors driven by varying magnetic forces.</p>

      <p> It exhibits a range of collective behaviors, including stable clustering, 
      wall-following, splitting and merging, and efficient obstacle navigation.</p>

      <div style="text-align: center;">
        <video width="350" controls>
          <source src="site.baseurl/assets/images/project_detail/swarm.mp4" type="video/mp4">
          Your browser does not support the video tag.
        </video>
      </div>


      <p style='text-align: center;'><b>Mission performing scenario of Swarm Robots</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Robot development, Collective Behaivor Experiment</p>
    tags:
      - Research
      - Swarm Robotics
      - Stimuli-responsive
    description: Swarm robotic system using magnetic forces for autonomous coordination and dynamic behavior
    id: satellite-explainability

  - title: Anti-noise canceling PCB module
    image: antinoise_PCB.jpg
    detail: >
      <p>The detection module filters sound sensor outputs (2kHz–5kHz) and triggers a 15V signal when the voltage exceeds 700mV.</p>
      
      <p>This was a project for the coursework 'Circuit Theory and Experiments'</p>
      <img src='site.baseurl/assets/images/project_detail/vibdetail.jpg' class='img-responsive' alt='keyscreen of our system'>

      <p style='text-align: center;'><b>Anti-noise canceling Circuit Design & PCB</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>PCB Design</p>
    tags:
      - PCB Design
      - Circuit Design
    description: PCB module designed to detect car horns and provide tactile alerts enhancing pedestrian awareness of approaching vehicles
    id: design_card
  - title: “Connecting the World with Engineering”
    image: Talkconcert.jpg
    link : https://stementor.tistory.com/entry/%EC%84%9C%EC%9A%B8%EB%8C%80%ED%95%99%EA%B5%90-%EA%B3%B5%EA%B3%BC%EB%8C%80%ED%95%99-%EC%9A%B0%EC%88%98%ED%95%99%EC%83%9D%EC%84%BC%ED%84%B0-%EA%B3%B5%EC%9A%B0-%ED%86%A0%ED%81%AC%EC%BD%98%EC%84%9C%ED%8A%B8-%EA%B3%B5%ED%95%99%EC%9C%BC%EB%A1%9C-%EC%84%B8%EC%83%81%EA%B3%BC-%EC%86%8C%ED%86%B5%ED%95%98%EB%8B%A4-%EC%B0%B8%EA%B0%80-%EC%8B%A0%EC%B2%AD-211%ED%86%A0
    detail: >
      <p>This is a leadership project by the 13th class of <a href='https://www.gongwoo.snu.ac.kr/'>STEM</a>, an honor society at Seoul National University.</p>

      <p>We hosted the 'Engineering Talk Concert' to make engineering more accessible to the public. 
      <br>The event was held on February 11th, 2023.<br></p>

      <img src='site.baseurl/assets/images/project_detail/talkdetail.jpg' class='img-responsive'
      style='max-width: 650px !important;' alt='K-MOOC project image'>

      <p style='text-align: center;'><b>Engineering Talk Concert Part 3</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Speaker, Organizer, Promoter</p>
    tags:
      - Community Outreach
      - Talk Concert
      - Engineering
    description: >-
      Engineering talk concert for 200 public audiences
    id: diarymate
  - detail: >
      <p>This is a leadership project by the 13th class of <a href='https://www.gongwoo.snu.ac.kr/'>STEM</a>, an honor society at Seoul National University.</p>

      <p>We hosted the 'Engineering Talk Concert' to make engineering more accessible to the public. 
      The event was held on February 11th, 2023.<br><br></p>

      <img src='site.baseurl/assets/images/project_detail/talkdetail.jpg' class='img-responsive'
      style='max-width: 650px !important;' alt='K-MOOC project image'>

      <p style='text-align: center;'><b>Engineering Talk Concert Part 3</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Running interview sessions, taking
      part in thematic analysis, analyzing log data, writing</p>
    tags:
      - CFD Flow Simulation
      - Metal Injection Molding
      - CNC Machining
    title: RC Car Manufacturing
    image: rccar.jpg
    paper: chi2023_mooc_paper.pdf
    description: Understanding how do older adults use online videos for learning
    id: kmooc
  - code: 'https://github.com/donghoon-io/KoSentimentAnalysis'
    detail: >
      <p>In this project, we are investigating methods to assist emotional support
      processes in online mental health community, particularly by leveraging
      AI.<br><br></p>

      <p>Specifically, to support their community interactions, we developed and
      deployed (i) multi-class sentiment detection model using BERT to support the
      affectionate feedback process and (ii) keyword extraction based on the
      saliency of each keywords to facilitate the experience-sharing
      processes.<br><br></p>

      <p>Co-advised by <a href='https://hwajunghong.com'>Hwajung Hong</a> and <a href='http://hcil.snu.ac.kr/people/jinwook-seo'>Jinwook Seo</a>, this work was published in <a href='https://chi2022.acm.org/'>CHI 2022
      Extended Abstracts</a> (Late-Breaking Work) and <a
      href='https://cis.unimelb.edu.au/hci/emotion-workshop'>CHI 2022 Workshop</a>
      (Future of Emotion in HCI).</p>

      <img src='site.baseurl/assets/images/project_detail/omhc.jpg' class='img-responsive'
      style='max-width: 650px !important;' alt='AI in OMHCs'>

      <p style='text-align: center;'><b>Keyscreens of our
      system</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Leading the project, preliminary
      interview, storyboarding, writing, system development</p>
    paper: chi2022_omhc_poster.pdf
    tags:
      - Research
      - <i class='fas fa-book'></i>&nbsp; CHI '22
      - Mental health
      - NLP
    image: stapler.jpg
    title: Revese Engineering
    description: Mechanical Analysis in Stapler
    id: omhc
  - category: personal
    code: 'https://github.com/donghoon-io/snu-crs-refresher'
    detail: >
      <p>Often referred to as a 'war', course registration process of Seoul
      National University is highly competitive as it is first come, first
      served.<br><br></p>

      <p>In this process, students sometimes accidentally reload the website,
      where the system immediately returns error message and forces user to log-in
      again. (I suspect this is to prvent users from using macro, but no one
      knows..) This is disastrous, since logging in makes users waste their times
      a lot in such a urgent situation.<br><br></p>

      <p>To address this, I made a browser extension, where users can simply click
      one button to escape from the error message. This tweak is supported on both
      <a
      href='https://chrome.google.com/webstore/detail/snu-crs-refresher/hhdokgcmhmpckjdhekdjpoaafoggaaan'>Chrome</a>
      and <a
      href='https://store.whale.naver.com/detail/dkhijlinmdhldgjbbpmmelahpbnhmpcc'>Whale</a>
      browser.</p>

      <img src='site.baseurl/assets/images/project_detail/crs.jpg' class='img-responsive' alt='SNU
      CRS project image'>

      <p style='text-align: center;'><b>Keyscreen of SNU CRS
      Refresher</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Independent project</p>
    tags:
      - Personal
      - Chrome
    image: crs.jpg
    title: SNU CRS Refresher
    description: >-
      Chrome extension for SNU course registration website that helps users escape
      from error message
    link: >-
      https://chrome.google.com/webstore/detail/snu-crs-refresher/hhdokgcmhmpckjdhekdjpoaafoggaaan
    id: crs
  - category: startup
    code: 'https://github.com/donghoon-io/spring2021crp'
    detail: >

      <p>This work was submitted as a team project assignment to the Spring 2021
      Creative Research Practice course.</p>

      <img src='site.baseurl/assets/images/project_detail/spring2021crp-1.jpg'
      class='img-responsive' alt='Spring 2021 creative research practice project
      first image'>

      <p style='text-align: center;'><b>Keyscreens of
      LOVEGORITHM</b></p>

      <img src='site.baseurl/assets/images/project_detail/spring2021crp-2.jpg'
      class='img-responsive' alt='Spring 2021 creative research practice project
      second image'>

      <p style='text-align: center;'><b>Keyscreen of LOVEGORITHM
      online user community</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Web development, prototype design,
      setting up dialogues, ideation</p>
    tags:
      - Coursework
      - Web
      - Speculative design
    image: kiwoom.jpg
    title: Kiwoomi
    description: Mobile Apps for Child Development and Parenting Management
    link: https://play.google.com/store/apps/details?id=com.solive.kiwoomi&hl=ko
    id: spring2021crp
  - category: schoolwork
    detail: >
      <p>We aimed to develop a very simple and small-sized system that generates vibration when detached or attached, creating a tactile feedback mechanism.</p>

      <p>The system is designed to be easily integrated into various devices, 
      providing users with a dynamic response to physical interaction. 
      This was used in  <a href="https://www.soliveventures.com/">Solive Ventures</a> prototype in sensory device.</p>

      <img src='site.baseurl/assets/images/project_detail/vibedetail.jpg' class='img-responsive'
      alt='vibrationmodule'>

      <p style='text-align: center;'><b>Vibration Module and modular toy application</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>PCB, Circuit Design, ideation, setting
      up dialogues</p>
    tags:
      - PCB Design
      - Circuit Design
      - Tactile Feedback
    image: simplevib.jpg
    title: VibeToggle
    description: A mini PCB module that generates vibration when detached or attached
    id: spring2021hci
